# Generated by Django 4.1.1 on 2022-10-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1111-12-12'),
            preserve_default=False,
        ),
    ]
