# Generated by Django 4.1.1 on 2022-10-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time',
            field=models.TimeField(default='11:11'),
            preserve_default=False,
        ),
    ]
